########################
# Config setup
########################
# This is an example config which overwrites the 'defaults.toml'

###### Pool specific info ###########

# Title of the site. Must not contain spaces or message signing will fail!
site_title = "SimpleCoinMulti"

# the FQDN
site_url = "http://www.simplecoinmulti.com"

# currency the pool owner gets paid in. This currency must be configured as
# an exchangeable currency. Additionally, the configuration guide's
# 'Payout currency' field defaults to this currency
pool_payout_currency = "LTC"

# Database setup
SECRET_KEY = "somethting_really_secret"
SQLALCHEMY_DATABASE_URI = "postgresql://<usr>:<pwd>@<url>:5432/<dbname>"

# Log at debug level
DEBUG = true

# Signature to match your settings in the SC RPC client
rpc_signature = "test"

# Notify users if using a PPAgent version older than this
latest_ppagent = [0, 3, 5]

# How many blocks to show by default
blocks_stats_page = 15

# Pass exchange fees to miners if True
charge_autoex_fees = false

# Ports/URL to show on quickstart guide
default_stratum_port = 3333
default_stratum_url = "stratum+tcp://"

# Payout chains
[chains.1]
title = "Litecoin + SYS MM"
currencies = ["SYS", "LTC"]
algo = "scrypt"
type = "pplns"
last_n = 2
fee_perc = "0.01"

# Server locations
[locations.CA]
location_acronym = "CA"
location = "Beauharnois, Canada"
country_flag = "/img/ca.svg"
address = "http://localhost"

# Custom currency configs
[currencies.LTC]
sellable = true
buyable = true
mineable = true
pool_payout_addr = "LbfSCZE1p9A3Yj2JK1n57kxyD2H1ZSXtNG"
[currencies.LTC.coinserv]
port = 20001
address = "127.0.0.1"
username = "admin1"
password = "123"

[currencies.SYS]
mineable = true
pool_payout_addr = "SdzKyvhD2Y3xJvGVSfx96NXszq6x9BZX34"
[currencies.SYS.coinserv]
port = 19001
address = "127.0.0.1"
username = "admin1"
password = "123"

# Each of these is a port which will be displayed on the configuration
# guide & pool stats
[mining_servers.1]
address = "localhost"
# The [stratum] part of the monitor address must match the key you
# use in PP for the stratum server
monitor_address = "http://localhost:3855/stratum"
port = 3333
location = "CA"
# diff can be set to any string, ie - for a vardiff port you may want 
# something like: diff = "8-256"
diff = 1
chain = 1